### ISSUE TITLE
Error when running watch

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/pathways-search#57]
I get this error when running ```npm run watch```

```sh
MacPro14:pathways-search dylanfong$ npm run watch

> pathways-search@1.0.0 watch /Users/dylanfong/Documents/workspace/work/pathway-commons-ecosystem/pathways-search
> webpack-dev-server --inline --content-base public/ -d

Project is running at http://localhost:8080/
webpack output is served from /
Content not from webpack is served from /Users/dylanfong/Documents/workspace/work/pathway-commons-ecosystem/pathways-search/public
Hash: 8709c385e81691969772
Version: webpack 2.3.3
Time: 13099ms
    Asset     Size  Chunks                    Chunk Names
bundle.js  14.1 MB       0  [emitted]  [big]  main
chunk    {0} bundle.js (main) 5.2 MB [entry] [rendered]
    [0] ./~/react/react.js 56 bytes {0} [built]
   [17] ./~/react-dom/index.js 59 bytes {0} [built]
   [57] ./~/react-router-dom/es/index.js 925 bytes {0} [built]
  [137] ./js/App.js 3.16 kB {0} [built]
  [352] (webpack)-dev-server/client?http://localhost:8080 5.44 kB {0} [built]
  [355] ./js/Index.jsx 6.63 kB {0} [built]
  [803] ./~/sockjs-client/lib/entry.js 244 bytes {0} [built]
  [830] ./~/strip-ansi/index.js 161 bytes {0} [built]
  [833] ./~/style-loader!./~/css-loader!./~/postcss-loader!./styles/index.css 1.02 kB {0} [built]
  [838] ./~/url/url.js 23.3 kB {0} [built]
  [839] ./~/url/util.js 314 bytes {0} [built]
  [844] (webpack)-dev-server/client/overlay.js 3.6 kB {0} [built]
  [845] (webpack)-dev-server/client/socket.js 856 bytes {0} [built]
  [847] (webpack)/hot/emitter.js 77 bytes {0} [built]
  [848] multi (webpack)-dev-server/client?http://localhost:8080 ./js/App.js 40 bytes {0} [built]
     + 834 hidden modules

ERROR in ./~/css-loader!./~/postcss-loader!./styles/index.css
Module build failed: TypeError: Loading PostCSS Plugin failed: Cannot read property 'stats' of undefined
    at /Users/dylanfong/Documents/workspace/work/pathway-commons-ecosystem/pathways-search/node_modules/postcss-cssnext/node_modules/caniuse-api/dist/index.js:68:16
    at Array.every (native)
    at isSupported (/Users/dylanfong/Documents/workspace/work/pathway-commons-ecosystem/pathways-search/node_modules/postcss-cssnext/node_modules/caniuse-api/dist/index.js:67:6)
    at /Users/dylanfong/Documents/workspace/work/pathway-commons-ecosystem/pathways-search/node_modules/postcss-cssnext/lib/index.js:69:117
    at Array.forEach (native)
    at /Users/dylanfong/Documents/workspace/work/pathway-commons-ecosystem/pathways-search/node_modules/postcss-cssnext/lib/index.js:56:35
    at creator (/Users/dylanfong/Documents/workspace/work/pathway-commons-ecosystem/pathways-search/node_modules/postcss/lib/postcss.js:150:35)
    at load (/Users/dylanfong/Documents/workspace/work/pathway-commons-ecosystem/pathways-search/node_modules/postcss-load-plugins/lib/plugins.js:52:33)
    at /Users/dylanfong/Documents/workspace/work/pathway-commons-ecosystem/pathways-search/node_modules/postcss-load-plugins/lib/plugins.js:66:18
    at Array.forEach (native)
 @ ./~/style-loader!./~/css-loader!./~/postcss-loader!./styles/index.css 4:14-114
 @ ./js/App.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./js/App.js
webpack: Failed to compile.
^C
```

What do I have to do to make it work?

**Comment by mj3cheun** [comment]
I have cloned the repository in a separate folder and it seems to compile fine. I suspect what happened here is you did `npm install` on the master branch and then switched to the integration branch. As the dependencies have changed, you must do `npm install` on the integration branch, and then try `npm run watch`.

**Comment by d2fong** [comment]
Ok thanks.  It works now.
